defaultPortal: votuan
portals:
  - name: votuan
    portalId: 19587306
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKLTh8GHLxIIAAkADAAA4AEY6sGrCSDplq8LKO7pDDIZAH2-YwUlNWHoJaJsP_fuuOl2wt7IR0SXijooAAAAQQAAAHgAAAAAAAAAAIABAAAAAAAAwADAB2D-_zEAAAAAAAAAYEIZAH2-YwUz4LvoJY_GO-Xre4mIZWG99FeHcEoDbmEx
        expiresAt: '2021-03-28T09:19:51.719Z'
    personalAccessKey: >-
      CiRiMWVmNzVhNi1lY2FhLTQwOWEtODViMi03Yzk3YzA5MjQxNjQQ6sGrCRjplq8LKhkABeaRgtqCbHI8JU_3r84qE8qejCeJCnPF
